import streamlit as st
from openai import OpenAI
import os
import base64
from PIL import Image
import io

# Initialize session state variables at the very beginning
if 'identified_ingredients' not in st.session_state:
    st.session_state.identified_ingredients = ""
if 'cuisine_shopping_list' not in st.session_state:
    st.session_state.cuisine_shopping_list = ""
if 'fridge_shopping_list' not in st.session_state:
    st.session_state.fridge_shopping_list = ""
if 'photo_shopping_list' not in st.session_state:
    st.session_state.photo_shopping_list = ""
if 'cuisine_recipe_content' not in st.session_state:
    st.session_state.cuisine_recipe_content = ""
if 'fridge_recipe_content' not in st.session_state:
    st.session_state.fridge_recipe_content = ""
if 'photo_recipe_content' not in st.session_state:
    st.session_state.photo_recipe_content = ""
if 'uploaded_photos' not in st.session_state:
    st.session_state.uploaded_photos = []
if 'all_identified_ingredients' not in st.session_state:
    st.session_state.all_identified_ingredients = ""
if 'cuisine_recipe_card' not in st.session_state:
    st.session_state.cuisine_recipe_card = ""
if 'fridge_recipe_card' not in st.session_state:
    st.session_state.fridge_recipe_card = ""
if 'photo_recipe_card' not in st.session_state:
    st.session_state.photo_recipe_card = ""

headers = {
    "authorization": st.secrets["api_key"],
    "content-type": "application/json"
}

# Set your OpenAI API key (make sure it's in your environment variables or you can paste it here for testing)
client = OpenAI(api_key=st.secrets["api_key"])

# Function to encode image to base64
def encode_image(image):
    buffered = io.BytesIO()
    image.save(buffered, format="JPEG")
    return base64.b64encode(buffered.getvalue()).decode()

# Function to generate shopping list from recipe
def generate_shopping_list(recipe_text, available_ingredients=""):
    try:
        prompt = f"""
        Based on this recipe: {recipe_text}
        
        {"And these ingredients I already have: " + available_ingredients if available_ingredients else ""}
        
        Please create a smart shopping list by:
        1. Extracting all ingredients from the recipe with quantities
        2. {"Separating what I already have vs. what I need to buy" if available_ingredients else "Listing all ingredients I need to buy"}
        3. Organizing by grocery store sections (Produce, Meat/Seafood, Dairy, Pantry, etc.)
        4. Including estimated quantities where specified in the recipe
        
        Format as:
        **SHOPPING LIST**
        
        **Produce:**
        - item (quantity)
        
        **Meat/Seafood:**
        - item (quantity)
        
        **Dairy:**
        - item (quantity)
        
        **Pantry/Dry Goods:**
        - item (quantity)
        
        **Other:**
        - item (quantity)
        
        {"**✅ Items you already have:**" + chr(10) + "- (list items from available ingredients that are used in recipe)" if available_ingredients else ""}
        
        Only include items that need to be purchased. Be specific about quantities when mentioned in the recipe.
        """
        
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful shopping assistant who creates organized grocery lists from recipes."},
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error generating shopping list: {e}"

# Function to generate print-friendly recipe card
def generate_recipe_card(recipe_text):
    try:
        prompt = f"""
        Based on this recipe: {recipe_text}
        
        Please create a beautifully formatted, print-friendly recipe card with the following structure:
        
        # [Recipe Name]
        
        **Servings:** [number]  |  **Prep Time:** [time]  |  **Cook Time:** [time]  |  **Total Time:** [time]
        
        ---
        
        ## Ingredients
        
        [List all ingredients with quantities, formatted clearly with bullet points]
        
        ---
        
        ## Instructions
        
        [Numbered step-by-step instructions, clear and concise]
        
        ---
        
        ## Tips & Notes
        
        [Any helpful tips, substitutions, or storage information]
        
        ---
        
        **Recipe generated by Dinner Recipe Maker**
        
        Please format this in a clean, organized way that would look great when printed. Use clear markdown formatting.
        If prep/cook times aren't specified in the original recipe, estimate reasonable times based on the recipe complexity.
        """
        
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant who creates beautifully formatted, print-friendly recipe cards."},
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error generating recipe card: {e}"

# Streamlit UI
st.title("Dinner Recipe Maker")

# Add tabs for different recipe modes
tab1, tab2, tab3 = st.tabs(["Recipe by Cuisine", "Recipe by Fridge Items", "Photo Recipe Finder"])

with tab1:
    st.header("Find Recipe by Cuisine & Preferences")
    
    # Cuisine dropdown
    cuisine = st.selectbox(
        "Select a cuisine type:",
        [
        "American",
        "Barbecue",
        "Chinese",
        "French",
        "Greek",
        "Indian",
        "Italian",
        "Japanese",
        "Korean",
        "Latin American",
        "Mediterranean",
        "Mexican",
        "Middle Eastern",
        "Seafood",
        "Southern/Soul Food",
        "Tex-Mex",
        "Thai",
        "Vegan/Vegetarian",
        "Vietnamese",
        "Other"
    ]
    )

    # Meal type and cooking preferences
    col1, col2 = st.columns(2)
    
    with col1:
        meal_type = st.selectbox(
            "What type of meal?",
            ["Dinner", "Lunch", "Breakfast/Brunch", "Appetizer", "Snack", "Dessert", "Side Dish"]
        )
        
        complexity = st.selectbox(
            "Select cooking complexity:",
            ["Easy", "Medium", "Hard"]
        )
    
    with col2:
        cooking_method = st.selectbox(
            "Preferred cooking method:",
            ["Any method", "One-pot/One-pan", "Slow cooker", "Air fryer", "Instant Pot/Pressure cooker", 
             "Oven/Baking", "Stovetop", "Grilling", "No-cook/Raw", "Microwave"]
        )
        
        portion_size = st.selectbox(
            "How many servings?",
            ["1 person", "2 people", "3-4 people (family)", "5-6 people", "Large group (8+ people)"]
        )

    # Dietary restrictions
    st.subheader("Dietary Preferences")
    col1, col2 = st.columns(2)
    
    with col1:
        vegetarian = st.checkbox("Vegetarian")
        vegan = st.checkbox("Vegan")
        gluten_free = st.checkbox("Gluten-free")
        dairy_free = st.checkbox("Dairy-free")
    
    with col2:
        keto = st.checkbox("Keto")
        paleo = st.checkbox("Paleo")
        low_carb = st.checkbox("Low-carb")
        low_sodium = st.checkbox("Low-sodium")
    
    # Allergy restrictions
    allergies = st.multiselect(
        "Any food allergies to avoid?",
        ["Nuts", "Shellfish", "Eggs", "Soy", "Fish", "Sesame", "Other"]
    )
    
    # Special instructions
    instructions = st.text_input("Any other special instructions or preferences?")

    # Submit button
    if st.button("Suggest Recipe", key="cuisine_recipe"):
        # Build dietary restrictions list
        dietary_restrictions = []
        if vegetarian: dietary_restrictions.append("vegetarian")
        if vegan: dietary_restrictions.append("vegan")
        if gluten_free: dietary_restrictions.append("gluten-free")
        if dairy_free: dietary_restrictions.append("dairy-free")
        if keto: dietary_restrictions.append("keto")
        if paleo: dietary_restrictions.append("paleo")
        if low_carb: dietary_restrictions.append("low-carb")
        if low_sodium: dietary_restrictions.append("low-sodium")
        
        prompt = f"Suggest a {complexity.lower()} {cuisine.lower()} {meal_type.lower()} recipe for {portion_size}"
        
        if cooking_method != "Any method":
            method_mapping = {
                "One-pot/One-pan": "one-pot or one-pan",
                "Slow cooker": "slow cooker",
                "Air fryer": "air fryer",
                "Instant Pot/Pressure cooker": "Instant Pot or pressure cooker",
                "Oven/Baking": "oven-baked",
                "Stovetop": "stovetop",
                "Grilling": "grilled",
                "No-cook/Raw": "no-cook",
                "Microwave": "microwave"
            }
            prompt += f" using {method_mapping[cooking_method]}"
        
        if dietary_restrictions:
            prompt += f" that is {', '.join(dietary_restrictions)}"
        
        if allergies:
            allergy_list = ', '.join([allergy.lower() for allergy in allergies])
            prompt += f". Avoid these allergens: {allergy_list}"
        
        if instructions:
            prompt += f". Also, consider this: {instructions}"
        prompt += ". Include ingredients and step-by-step instructions."

        # Make request to OpenAI
        try:
            response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are a helpful chef assistant."},
                    {"role": "user", "content": prompt}
                ]
            )
            recipe_content = response.choices[0].message.content
            st.session_state.cuisine_recipe_content = recipe_content
            # Clear shopping list when new recipe is generated
            st.session_state.cuisine_shopping_list = ""
        except Exception as e:
            st.error(f"An error occurred: {e}")
    
    # Display recipe if it exists in session state
    if st.session_state.cuisine_recipe_content:
        st.markdown("### Suggested Recipe")
        st.write(st.session_state.cuisine_recipe_content)
        
        # Add shopping list and recipe card generation
        st.markdown("---")
        col1, col2 = st.columns(2)
        
        with col1:
            if st.button("🛒 Generate Shopping List", key="cuisine_shopping_list_btn"):
                with st.spinner("Creating your shopping list..."):
                    shopping_list = generate_shopping_list(st.session_state.cuisine_recipe_content)
                    st.session_state.cuisine_shopping_list = shopping_list
        
        with col2:
            if st.button("🖨️ Create Recipe Card", key="cuisine_recipe_card_btn"):
                with st.spinner("Creating your recipe card..."):
                    recipe_card = generate_recipe_card(st.session_state.cuisine_recipe_content)
                    st.session_state.cuisine_recipe_card = recipe_card
        
        # Display shopping list if it exists
        if st.session_state.cuisine_shopping_list:
            st.markdown("### 🛒 Smart Shopping List")
            st.write(st.session_state.cuisine_shopping_list)
        
        # Display recipe card if it exists
        if st.session_state.cuisine_recipe_card:
            st.markdown("### 🖨️ Print-Friendly Recipe Card")
            st.info("💡 Tip: Use your browser's print function (Ctrl+P or Cmd+P) to print or save as PDF")
            st.markdown(st.session_state.cuisine_recipe_card)
            
            # Add a download button for the recipe card
            st.download_button(
                label="📥 Download Recipe Card as Text",
                data=st.session_state.cuisine_recipe_card,
                file_name="recipe_card.txt",
                mime="text/plain",
                key="download_cuisine_recipe_card"
            )

with tab2:
    st.header("Find Recipe by What's in Your Fridge")
    
    # Fridge items input
    st.subheader("What ingredients do you have?")
    fridge_items = st.text_area(
        "List the ingredients you have available (separate with commas):",
        placeholder="e.g., chicken, rice, onions, bell peppers, garlic, tomatoes",
        height=100
    )
    
    # Additional preferences for fridge mode
    st.subheader("Preferences")
    # Meal type and cooking preferences for fridge mode
    col1, col2 = st.columns(2)
    
    with col1:
        fridge_meal_type = st.selectbox(
            "What type of meal?",
            ["Dinner", "Lunch", "Breakfast/Brunch", "Appetizer", "Snack", "Dessert", "Side Dish"],
            key="fridge_meal_type"
        )
        
        fridge_complexity = st.selectbox(
            "Cooking complexity:",
            ["Easy", "Medium", "Hard"],
            key="fridge_complexity"
        )
    
    with col2:
        fridge_cooking_method = st.selectbox(
            "Preferred cooking method:",
            ["Any method", "One-pot/One-pan", "Slow cooker", "Air fryer", "Instant Pot/Pressure cooker", 
             "Oven/Baking", "Stovetop", "Grilling", "No-cook/Raw", "Microwave"],
            key="fridge_cooking_method"
        )
        
        fridge_portion_size = st.selectbox(
            "How many servings?",
            ["1 person", "2 people", "3-4 people (family)", "5-6 people", "Large group (8+ people)"],
            key="fridge_portion_size"
        )
    # Time and ingredient preferences
    col3, col4 = st.columns(2)
    
    with col3:
        cooking_time = st.selectbox(
            "How much time do you have?",
            ["Quick (under 30 min)", "Medium (30-60 min)", "I have time (60+ min)"]
        )
    
    with col4:
        allow_additional = st.checkbox(
            "Allow recipes that need a few additional common ingredients?",
            value=True,
            help="If checked, recipes may include common pantry items you might not have listed"
        )
    
    # Dietary restrictions for fridge mode
    st.subheader("Dietary Preferences")
    col3, col4 = st.columns(2)
    
    with col3:
        fridge_vegetarian = st.checkbox("Vegetarian", key="fridge_vegetarian")
        fridge_vegan = st.checkbox("Vegan", key="fridge_vegan")
        fridge_gluten_free = st.checkbox("Gluten-free", key="fridge_gluten_free")
        fridge_dairy_free = st.checkbox("Dairy-free", key="fridge_dairy_free")
    
    with col4:
        fridge_keto = st.checkbox("Keto", key="fridge_keto")
        fridge_paleo = st.checkbox("Paleo", key="fridge_paleo")
        fridge_low_carb = st.checkbox("Low-carb", key="fridge_low_carb")
        fridge_low_sodium = st.checkbox("Low-sodium", key="fridge_low_sodium")
    
    # Allergy restrictions for fridge mode
    fridge_allergies = st.multiselect(
        "Any food allergies to avoid?",
        ["Nuts", "Shellfish", "Eggs", "Soy", "Fish", "Sesame", "Other"],
        key="fridge_allergies"
    )
    
    # Special dietary restrictions or preferences
    fridge_instructions = st.text_input(
        "Any dietary restrictions or special requests?",
        key="fridge_instructions"
    )

    # Submit button for fridge mode
    if st.button("Find Recipe with My Ingredients", key="fridge_recipe"):
        if not fridge_items.strip():
            st.warning("Please enter at least some ingredients from your fridge!")
        else:
            # Build prompt for fridge-based recipe
            time_mapping = {
                "Quick (under 30 min)": "quick and easy, taking less than 30 minutes",
                "Medium (30-60 min)": "moderate cooking time, around 30-60 minutes", 
                "I have time (60+ min)": "can take longer to prepare, 60+ minutes"
            }
            
            # Build dietary restrictions list for fridge mode
            fridge_dietary_restrictions = []
            if fridge_vegetarian: fridge_dietary_restrictions.append("vegetarian")
            if fridge_vegan: fridge_dietary_restrictions.append("vegan")
            if fridge_gluten_free: fridge_dietary_restrictions.append("gluten-free")
            if fridge_dairy_free: fridge_dietary_restrictions.append("dairy-free")
            if fridge_keto: fridge_dietary_restrictions.append("keto")
            if fridge_paleo: fridge_dietary_restrictions.append("paleo")
            if fridge_low_carb: fridge_dietary_restrictions.append("low-carb")
            if fridge_low_sodium: fridge_dietary_restrictions.append("low-sodium")
            
            prompt = f"I have these ingredients available: {fridge_items}. "
            prompt += f"Please suggest a {fridge_complexity.lower()} {fridge_meal_type.lower()} recipe for {fridge_portion_size} that is {time_mapping[cooking_time]}"
            
            if fridge_cooking_method != "Any method":
                method_mapping = {
                    "One-pot/One-pan": "one-pot or one-pan",
                    "Slow cooker": "slow cooker",
                    "Air fryer": "air fryer",
                    "Instant Pot/Pressure cooker": "Instant Pot or pressure cooker",
                    "Oven/Baking": "oven-baked",
                    "Stovetop": "stovetop",
                    "Grilling": "grilled",
                    "No-cook/Raw": "no-cook",
                    "Microwave": "microwave"
                }
                prompt += f" using {method_mapping[fridge_cooking_method]}"
            
            if fridge_dietary_restrictions:
                prompt += f" and {', '.join(fridge_dietary_restrictions)}"
            
            if fridge_allergies:
                fridge_allergy_list = ', '.join([allergy.lower() for allergy in fridge_allergies])
                prompt += f". Avoid these allergens: {fridge_allergy_list}"
            
            if allow_additional:
                prompt += ". You can suggest recipes that use most of these ingredients and may require a few common pantry staples (like oil, salt, pepper, basic spices) that most people have."
            else:
                prompt += ". Please try to use primarily the ingredients I've listed."
            
            if fridge_instructions:
                prompt += f" Also consider: {fridge_instructions}"
            
            prompt += " Include a complete ingredient list (highlighting what I already have vs. what I might need to get) and step-by-step cooking instructions."

            # Make request to OpenAI
            try:
                response = client.chat.completions.create(
                    model="gpt-3.5-turbo",
                    messages=[
                        {"role": "system", "content": "You are a helpful chef assistant who specializes in creating recipes based on available ingredients. Always clearly indicate which ingredients the user already has vs. which they might need to purchase."},
                        {"role": "user", "content": prompt}
                    ]
                )
                recipe_content = response.choices[0].message.content
                st.session_state.fridge_recipe_content = recipe_content
                # Clear shopping list when new recipe is generated
                st.session_state.fridge_shopping_list = ""
            except Exception as e:
                st.error(f"An error occurred: {e}")
    
    # Display recipe if it exists in session state
    if st.session_state.fridge_recipe_content:
        st.markdown("### Recipe Based on Your Ingredients")
        st.write(st.session_state.fridge_recipe_content)
        
        # Add shopping list and recipe card generation
        st.markdown("---")
        col1, col2 = st.columns(2)
        
        with col1:
            if st.button("🛒 Generate Shopping List", key="fridge_shopping_list_btn"):
                with st.spinner("Creating your shopping list..."):
                    # Get the current fridge items from the text area
                    current_fridge_items = st.session_state.get('fridge_items_current', fridge_items)
                    shopping_list = generate_shopping_list(st.session_state.fridge_recipe_content, current_fridge_items)
                    st.session_state.fridge_shopping_list = shopping_list
        
        with col2:
            if st.button("🖨️ Create Recipe Card", key="fridge_recipe_card_btn"):
                with st.spinner("Creating your recipe card..."):
                    recipe_card = generate_recipe_card(st.session_state.fridge_recipe_content)
                    st.session_state.fridge_recipe_card = recipe_card
        
        # Display shopping list if it exists
        if st.session_state.fridge_shopping_list:
            st.markdown("### 🛒 Smart Shopping List")
            st.write(st.session_state.fridge_shopping_list)
        
        # Display recipe card if it exists
        if st.session_state.fridge_recipe_card:
            st.markdown("### 🖨️ Print-Friendly Recipe Card")
            st.info("💡 Tip: Use your browser's print function (Ctrl+P or Cmd+P) to print or save as PDF")
            st.markdown(st.session_state.fridge_recipe_card)
            
            # Add a download button for the recipe card
            st.download_button(
                label="📥 Download Recipe Card as Text",
                data=st.session_state.fridge_recipe_card,
                file_name="recipe_card.txt",
                mime="text/plain",
                key="download_fridge_recipe_card"
            )

with tab3:
    st.header("Photo Recipe Finder")
    st.write("Take a photo of your fridge, pantry, or ingredients and I'll identify what you have and suggest recipes!")
    
    # Camera input
    camera_photo = st.camera_input("Take a photo of your ingredients")
    
    # Initialize session state for identified ingredients
    if 'identified_ingredients' not in st.session_state:
        st.session_state.identified_ingredients = ""
    
    if camera_photo is not None:
        # Display the photo
        st.image(camera_photo, caption="Your ingredient photo", width=300)
        
        # Button to analyze the photo
        if st.button("🔍 Identify Ingredients in Photo", key="analyze_photo"):
            with st.spinner("Analyzing your photo..."):
                try:
                    # Convert the image to PIL format
                    image = Image.open(camera_photo)
                    
                    # Encode image to base64
                    base64_image = encode_image(image)
                    
                    # Make request to OpenAI Vision API
                    response = client.chat.completions.create(
                        model="gpt-4o",
                        messages=[
                            {
                                "role": "user",
                                "content": [
                                    {
                                        "type": "text",
                                        "text": "Please identify all the food ingredients, items, and products you can see in this image. List them as a comma-separated list. Focus on ingredients that could be used for cooking. Include fresh produce, packaged goods, dairy products, meats, spices, condiments, etc. Be specific about types (e.g., 'red bell peppers' instead of just 'peppers'). Only list food items that are clearly visible and identifiable."
                                    },
                                    {
                                        "type": "image_url",
                                        "image_url": {
                                            "url": f"data:image/jpeg;base64,{base64_image}"
                                        }
                                    }
                                ]
                            }
                        ],
                        max_tokens=500
                    )
                    
                    # Store identified ingredients in session state
                    st.session_state.identified_ingredients = response.choices[0].message.content
                    
                    st.success("✅ Ingredients identified!")
                    
                except Exception as e:
                    st.error(f"Error analyzing image: {e}")
    
    # Display and allow editing of identified ingredients
    if st.session_state.identified_ingredients:
        st.subheader("📝 Identified Ingredients")
        
        # Editable text area with identified ingredients
        photo_ingredients = st.text_area(
            "Review and edit the ingredients I found:",
            value=st.session_state.identified_ingredients,
            height=120,
            help="You can add, remove, or modify any ingredients before generating a recipe"
        )
        
        # Recipe preferences for photo mode
        st.subheader("Recipe Preferences")
        
        col1, col2 = st.columns(2)
        
        with col1:
            photo_meal_type = st.selectbox(
                "What type of meal?",
                ["Dinner", "Lunch", "Breakfast/Brunch", "Appetizer", "Snack", "Dessert", "Side Dish"],
                key="photo_meal_type"
            )
            
            photo_complexity = st.selectbox(
                "Cooking complexity:",
                ["Easy", "Medium", "Hard"],
                key="photo_complexity"
            )
        
        with col2:
            photo_cooking_method = st.selectbox(
                "Preferred cooking method:",
                ["Any method", "One-pot/One-pan", "Slow cooker", "Air fryer", "Instant Pot/Pressure cooker", 
                 "Oven/Baking", "Stovetop", "Grilling", "No-cook/Raw", "Microwave"],
                key="photo_cooking_method"
            )
            
            photo_portion_size = st.selectbox(
                "How many servings?",
                ["1 person", "2 people", "3-4 people (family)", "5-6 people", "Large group (8+ people)"],
                key="photo_portion_size"
            )
        
        # Time and additional ingredients
        col3, col4 = st.columns(2)
        
        with col3:
            photo_cooking_time = st.selectbox(
                "How much time do you have?",
                ["Quick (under 30 min)", "Medium (30-60 min)", "I have time (60+ min)"],
                key="photo_cooking_time"
            )
        
        with col4:
            photo_allow_additional = st.checkbox(
                "Allow recipes that need a few additional common ingredients?",
                value=True,
                key="photo_allow_additional",
                help="If checked, recipes may include common pantry items you might not have"
            )
        
        # Dietary restrictions for photo mode
        st.subheader("Dietary Preferences")
        col5, col6 = st.columns(2)
        
        with col5:
            photo_vegetarian = st.checkbox("Vegetarian", key="photo_vegetarian")
            photo_vegan = st.checkbox("Vegan", key="photo_vegan")
            photo_gluten_free = st.checkbox("Gluten-free", key="photo_gluten_free")
            photo_dairy_free = st.checkbox("Dairy-free", key="photo_dairy_free")
        
        with col6:
            photo_keto = st.checkbox("Keto", key="photo_keto")
            photo_paleo = st.checkbox("Paleo", key="photo_paleo")
            photo_low_carb = st.checkbox("Low-carb", key="photo_low_carb")
            photo_low_sodium = st.checkbox("Low-sodium", key="photo_low_sodium")
        
        # Allergy restrictions for photo mode
        photo_allergies = st.multiselect(
            "Any food allergies to avoid?",
            ["Nuts", "Shellfish", "Eggs", "Soy", "Fish", "Sesame", "Other"],
            key="photo_allergies"
        )
        
        # Special instructions for photo mode
        photo_instructions = st.text_input(
            "Any special instructions or preferences?",
            key="photo_instructions"
        )
        
        # Generate recipe button
        if st.button("🍳 Generate Recipe from Photo", key="photo_recipe"):
            if not photo_ingredients.strip():
                st.warning("Please make sure there are ingredients listed above!")
            else:
                # Build prompt for photo-based recipe
                time_mapping = {
                    "Quick (under 30 min)": "quick and easy, taking less than 30 minutes",
                    "Medium (30-60 min)": "moderate cooking time, around 30-60 minutes", 
                    "I have time (60+ min)": "can take longer to prepare, 60+ minutes"
                }
                
                # Build dietary restrictions list for photo mode
                photo_dietary_restrictions = []
                if photo_vegetarian: photo_dietary_restrictions.append("vegetarian")
                if photo_vegan: photo_dietary_restrictions.append("vegan")
                if photo_gluten_free: photo_dietary_restrictions.append("gluten-free")
                if photo_dairy_free: photo_dietary_restrictions.append("dairy-free")
                if photo_keto: photo_dietary_restrictions.append("keto")
                if photo_paleo: photo_dietary_restrictions.append("paleo")
                if photo_low_carb: photo_dietary_restrictions.append("low-carb")
                if photo_low_sodium: photo_dietary_restrictions.append("low-sodium")
                
                prompt = f"Based on these ingredients I have from my photo: {photo_ingredients}. "
                prompt += f"Please suggest a {photo_complexity.lower()} {photo_meal_type.lower()} recipe for {photo_portion_size} that is {time_mapping[photo_cooking_time]}"
                
                if photo_cooking_method != "Any method":
                    method_mapping = {
                        "One-pot/One-pan": "one-pot or one-pan",
                        "Slow cooker": "slow cooker",
                        "Air fryer": "air fryer",
                        "Instant Pot/Pressure cooker": "Instant Pot or pressure cooker",
                        "Oven/Baking": "oven-baked",
                        "Stovetop": "stovetop",
                        "Grilling": "grilled",
                        "No-cook/Raw": "no-cook",
                        "Microwave": "microwave"
                    }
                    prompt += f" using {method_mapping[photo_cooking_method]}"
                
                if photo_dietary_restrictions:
                    prompt += f" and {', '.join(photo_dietary_restrictions)}"
                
                if photo_allergies:
                    photo_allergy_list = ', '.join([allergy.lower() for allergy in photo_allergies])
                    prompt += f". Avoid these allergens: {photo_allergy_list}"
                
                if photo_allow_additional:
                    prompt += ". You can suggest recipes that use most of these ingredients and may require a few common pantry staples (like oil, salt, pepper, basic spices) that most people have."
                else:
                    prompt += ". Please try to use primarily the ingredients I've identified from my photo."
                
                if photo_instructions:
                    prompt += f" Also consider: {photo_instructions}"
                
                prompt += " Include a complete ingredient list (highlighting what I already have from the photo vs. what I might need to get) and step-by-step cooking instructions."

                # Make request to OpenAI
                try:
                    with st.spinner("Creating your recipe..."):
                        response = client.chat.completions.create(
                            model="gpt-3.5-turbo",
                            messages=[
                                {"role": "system", "content": "You are a helpful chef assistant who specializes in creating recipes based on ingredients identified from photos. Always clearly indicate which ingredients the user already has vs. which they might need to purchase."},
                                {"role": "user", "content": prompt}
                            ]
                        )
                        recipe_content = response.choices[0].message.content
                        st.session_state.photo_recipe_content = recipe_content
                        # Clear shopping list when new recipe is generated
                        st.session_state.photo_shopping_list = ""
                except Exception as e:
                    st.error(f"An error occurred while generating the recipe: {e}")
        
        # Display recipe if it exists in session state
        if st.session_state.photo_recipe_content:
            st.markdown("### 📸 Recipe Based on Your Photo")
            st.write(st.session_state.photo_recipe_content)
            
            # Add shopping list generation for photo recipes
            st.markdown("---")
            if st.button("🛒 Generate Shopping List", key="photo_shopping_list_btn"):
                with st.spinner("Creating your shopping list..."):
                    shopping_list = generate_shopping_list(st.session_state.photo_recipe_content, photo_ingredients)
                    st.session_state.photo_shopping_list = shopping_list
            
            # Display shopping list if it exists
            if st.session_state.photo_shopping_list:
                st.markdown("### 🛒 Smart Shopping List")
                st.write(st.session_state.photo_shopping_list)
    
    else:
        st.info("👆 Take a photo of your ingredients to get started!")
        st.markdown("""
        **Tips for better ingredient identification:**
        - Make sure ingredients are well-lit and clearly visible
        - Try to capture labels on packaged items
        - Spread items out so they're not overlapping
        - Take the photo from a good angle where items are recognizable
        """)
